/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CommentControllerService } from './services/comment.service';
export { CategoryControllerService } from './services/category.service';
export { CrudRestApIsForPostResourceService } from './services/post.service';
