/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createPost } from '../fn/crud-rest-ap-is-for-post-resource/create-post';
import { CreatePost$Params } from '../fn/crud-rest-ap-is-for-post-resource/create-post';
import { deletePost } from '../fn/crud-rest-ap-is-for-post-resource/delete-post';
import { DeletePost$Params } from '../fn/crud-rest-ap-is-for-post-resource/delete-post';
import { getAllPosts } from '../fn/crud-rest-ap-is-for-post-resource/get-all-posts';
import { GetAllPosts$Params } from '../fn/crud-rest-ap-is-for-post-resource/get-all-posts';
import { getPostById } from '../fn/crud-rest-ap-is-for-post-resource/get-post-by-id';
import { GetPostById$Params } from '../fn/crud-rest-ap-is-for-post-resource/get-post-by-id';
import { getPostsByCategory } from '../fn/crud-rest-ap-is-for-post-resource/get-posts-by-category';
import { GetPostsByCategory$Params } from '../fn/crud-rest-ap-is-for-post-resource/get-posts-by-category';
import { PostDto } from '../models/post-dto';
import { PostResponse } from '../models/post-response';
import { updatePost } from '../fn/crud-rest-ap-is-for-post-resource/update-post';
import { UpdatePost$Params } from '../fn/crud-rest-ap-is-for-post-resource/update-post';

@Injectable({ providedIn: 'root' })
export class PostService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getPostById()` */
  static readonly GetPostByIdPath = '/api/posts/{id}';

  /**
   * Get Post By Id REST API.
   *
   * Get Post By Id REST API is used to get single post from the database
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPostById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostById$Response(params: GetPostById$Params, context?: HttpContext): Observable<StrictHttpResponse<PostDto>> {
    return getPostById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Post By Id REST API.
   *
   * Get Post By Id REST API is used to get single post from the database
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPostById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostById(params: GetPostById$Params, context?: HttpContext): Observable<PostDto> {
    return this.getPostById$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostDto>): PostDto => r.body)
    );
  }

  /** Path part for operation `updatePost()` */
  static readonly UpdatePostPath = '/api/posts/{id}';

  /**
   * update Post REST API.
   *
   * Update Post REST API is used to update a particular post in the database
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePost$Response(params: UpdatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostDto>> {
    return updatePost(this.http, this.rootUrl, params, context);
  }

  /**
   * update Post REST API.
   *
   * Update Post REST API is used to update a particular post in the database
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePost(params: UpdatePost$Params, context?: HttpContext): Observable<PostDto> {
    return this.updatePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostDto>): PostDto => r.body)
    );
  }

  /** Path part for operation `deletePost()` */
  static readonly DeletePostPath = '/api/posts/{id}';

  /**
   * Delete Post REST API.
   *
   * Delete Post REST API is used to delete a particular post from the database
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deletePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePost$Response(params: DeletePost$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return deletePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete Post REST API.
   *
   * Delete Post REST API is used to delete a particular post from the database
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deletePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePost(params: DeletePost$Params, context?: HttpContext): Observable<string> {
    return this.deletePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getAllPosts()` */
  static readonly GetAllPostsPath = '/api/posts';

  /**
   * Get All Posts REST API.
   *
   * Get All Posts REST API is used to fetch all the posts from the database
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllPosts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPosts$Response(params?: GetAllPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponse>> {
    return getAllPosts(this.http, this.rootUrl, params, context);
  }

  /**
   * Get All Posts REST API.
   *
   * Get All Posts REST API is used to fetch all the posts from the database
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllPosts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPosts(params?: GetAllPosts$Params, context?: HttpContext): Observable<PostResponse> {
    return this.getAllPosts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostResponse>): PostResponse => r.body)
    );
  }

  /** Path part for operation `createPost()` */
  static readonly CreatePostPath = '/api/posts';

  /**
   * Create Post REST API.
   *
   * Create Post REST API is used to save post into database
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPost$Response(params: CreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostDto>> {
    return createPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create Post REST API.
   *
   * Create Post REST API is used to save post into database
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPost(params: CreatePost$Params, context?: HttpContext): Observable<PostDto> {
    return this.createPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostDto>): PostDto => r.body)
    );
  }

  /** Path part for operation `getPostsByCategory()` */
  static readonly GetPostsByCategoryPath = '/api/posts/category/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPostsByCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostsByCategory$Response(params: GetPostsByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PostDto>>> {
    return getPostsByCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPostsByCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostsByCategory(params: GetPostsByCategory$Params, context?: HttpContext): Observable<Array<PostDto>> {
    return this.getPostsByCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PostDto>>): Array<PostDto> => r.body)
    );
  }

}
