/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommentDto } from '../models/comment-dto';
import { CategoryDto } from './category-dto';

/**
 * PostDto Model Information
 */
export interface PostDto {

  /**
   * Blog Post Category
   */
  category?: CategoryDto;
  comments?: Array<CommentDto>;

  /**
   * Blog Post Content
   */
  content?: string;

  /**
   * Blog Post Description
   */
  description?: string;
  id?: number;

  /**
   * Blog Post Title
   */
  title?: string;
}
