/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryDto } from './models/category-dto';
export type { CommentDto } from './models/comment-dto';
export type { PostDto } from './models/post-dto';
export type { PostResponse } from './models/post-response';
